### ISSUE TITLE
Support USB 3.0 (USB Attached SCSI)

### ISSUE THREAD

**Issue by haoxi911** [alphadev-net/drive-mount#69]
I realized the library works well with USB 2.0 drives, but not USB 3.0 drives. I was told this is because the USB 3.0 drives need UASP (USB Attached SCSI Protocol) support. Do we have any plan to support this feature or is it already supported?

https://en.wikipedia.org/wiki/USB_Attached_SCSI

**Comment by janseeger** [comment]
AFAIK USB 3.0 should be backward compatible with 2.0 so there is a good chance the drive mount app does get the handshake wrong. Also if I correctly remember UASP uses multiple IO channels to achieve those speeds which the app architecture doesn't support at the moment.

**Comment by haoxi911** [comment]
The OTG library [libaums](https://github.com/magnusja/libaums) works well with USB 3.0 drives, it also contains a lightweight HTTP server to allow web access to drive files.
